FIND-17: Интеграция нового бэкенда
VikhlyaevSergey/Find pull request #23
Opened 2021-05-23 10:40 UTC by sa1dai

2021-05-24 08:58 UTC, VikhlyaevSergey requested changes

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Common/AccountManagment/AccountManagmentAPI.swift
> +    func requestOwnerProfile()->Promise<DefaultResponse<ProfileAPIObject>> {
Доки нет на. публичный метод

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Common/AccountManagment/AccountManagmentAPI.swift
>  class AccountManagmentApi {
final

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Common/RoutingAssistant.swift
> +	func constructStartViewController(completion: @escaping (_ startViewController: UIViewController?) -> ())
Дока на протокол и методы

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Default/AppDelegate.swift
> +		// важно, что устанавливаем self.window здесь, а не внутри closure routingAssistant.constructStartViewController, иначе может быть черный экран при запуске приложения
👍

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Models/ProfileModels.swift
> +	var profileFavouriteLossObjects: [String]? = []
либо ? либо []

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Models/ProfileModels.swift
> +final class ProfileAPIObject: Codable {
Кайф

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Enter/EnterAPI/EnterRequest.swift
> +    case codeRequest(String)
кейсы тоже документируются в идеале

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Enter/EnterAPI/LoginResponse.swift
> -struct VerifyPhoneResponse: Codable {
Зря удалил, надо было оставить, просто использовать другое

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Enter/EnterInteractor.swift
> +    func codeRequest(completion: @escaping (Bool, String?, Int?, Error?) -> ())
доки

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Enter/EnterInteractor.swift
// MARK: - EnterBusinessLogic

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Enter/EnterPresenter.swift
>  protocol EnterViewControllerOutput {
Доки

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Enter/EnterPresenter.swift
// MARK: - EnterViewControllerOutput

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Enter/EnterViewController.swift
> +    func codeRequest(phoneNumber: String)
Доки

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Enter/Views/PhoneNumberView.swift
>          //delegate?.next()
Удаляем мёртвый код

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/Registration/RegistrationAPI/RegistrationAPI.swift
>  class RegistrationApi {
final

2021-05-24 08:58 UTC, VikhlyaevSergey commented on Find/Modules/TabBar/Profile/ProfileInteractor.swift
> +// 		на данный момент запрос при выходе делать не нужно
ок, пусть пока что так

2021-05-24 11:56 UTC, sa1dai commented on Find/Modules/Enter/EnterAPI/LoginResponse.swift
> -struct VerifyPhoneResponse: Codable {
Не понял, я не удалял совсем, а переименовал в LoginResponse

2021-05-24 12:25 UTC, sa1dai commented on Find/Modules/Enter/EnterInteractor.swift
EnterInteractor здесь не реализует протокол EnterBusinessLogic

2021-05-24 12:48 UTC, sa1dai commented on Find/Modules/Enter/EnterPresenter.swift
EnterPresenter здесь не реализует протокол EnterViewControllerOutput

2021-05-25 09:06 UTC, VikhlyaevSergey approved these changes

2021-05-25 09:07 UTC, merged